name: Run Selected Selenium Tests with Validation
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3
 
      - name: ☕ Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: 🧪 Print Chrome version
        run: google-chrome --version
 
      - name: 🚀 Run Selenium Tests with Summary Extraction and Validation
        env:
          GITHUB_ACTIONS: true
        run: |
          echo "================ RUNNING TESTS ================="
          CHROME_ARGS="--headless=new --no-sandbox --disable-dev-shm-usage --window-size=1920,1080"
 
          # Run selected tests and capture output
          mvn clean test -Dtest=essential.LoginLogout,essential.AddDepartment,essential.EmployeeOnboarding,enterprise.ExpenseManagement | tee selenium-test-output.txt
 
          echo "================ FILTERING SUMMARY ================="
          grep -E 'EMPLOYEE ONBOARDING|LOGIN AND LOGOUT|ADD DEPARTMENT AND DELETE DEPARTMENT|done successfully|completed|successful' selenium-test-output.txt > test-summary.txt
 
          echo "================ PARSING RESULTS ================="
          summary_line=$(grep "Tests run:" selenium-test-output.txt | tail -1)
          echo "Test Summary: $summary_line"
 
          total=$(echo "$summary_line" | grep -oP 'Tests run: \K[0-9]+')
          failures=$(echo "$summary_line" | grep -oP 'Failures: \K[0-9]+')
          errors=$(echo "$summary_line" | grep -oP 'Errors: \K[0-9]+')
          skipped=$(echo "$summary_line" | grep -oP 'Skipped: \K[0-9]+')
          passed=$((total - failures - errors))
 
          if [ "$total" -eq 0 ]; then
            percent=0
          else
            percent=$((passed * 100 / total))
          fi
 
          echo "📊 Total: $total, Passed: $passed, Failures: $failures, Errors: $errors, Skipped: $skipped, Passed %: $percent" | tee test-validation-summary.txt
 
          if [ "$percent" -lt 80 ]; then
            echo "❌ Test pass percentage ($percent%) is below threshold (80%). Failing the pipeline." | tee -a test-validation-summary.txt
            exit 1
          else
            echo "✅ Test pass percentage ($percent%) is acceptable. Proceeding." | tee -a test-validation-summary.txt
          fi
 
      - name: 📦 Upload validation summary
        uses: actions/upload-artifact@v4
        with:
          name: test-validation-summary
          path: test-validation-summary.txt
 
      - name: 📦 Upload full Maven test log
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-output
          path: selenium-test-output.txt
 
      - name: 📦 Upload test summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-summary
          path: test-summary.txt
